name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 3.9+ is not currently supported due to https://github.com/freach/udatetime/issues/32
        python-version: ["3.8", "3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ST2 Test Runner
        run: |
          python3 -m pip install virtualenv
          git clone --depth=1 https://github.com/StackStorm/st2.git /tmp/st2
          sudo apt-get update
          # Required to get python-ldap wheel building
          sudo apt-get install -y --no-install-recommends libsasl2-dev python3-dev libldap2-dev libssl-dev

      - name: Run Tests
        run: ST2_REPO_PATH=/tmp/st2 /tmp/st2/st2common/bin/st2-run-pack-tests -p . -c

      - name: Generate Coverage
        run: |
          python3 -m pip install coverage~=4.4
          coverage xml

      - name: Submit Coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
